name: duelPlugin
main: me.hughjph.duelPlugin.Main
version: 1.0
api-version: 1.16


commands:
  duel:
    description: sends a duel challenge to a player
  a:
    description: accepts duel


permissions:
  duelplugin.feature:
    default: op